/* tslint:disable */
/* eslint-disable */
/**
 * SpotReservation.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AuthResponse {
    'userId': string;
    'email': string;
    'role': string;
    'token': string;
    'expiresAtUtc': string;
}
export interface Coordinate {
    'x'?: number;
    'y'?: number;
    'z'?: number;
    'm'?: number;
    'coordinateValue'?: Coordinate | null;
    'isValid'?: boolean;
}
export interface Coordinate2 {
    'x'?: number;
    'y'?: number;
    'z'?: number;
    'm'?: number;
    'coordinateValue'?: Coordinate | null;
    'isValid'?: boolean;
}
export interface Coordinate3 {
    'x'?: number;
    'y'?: number;
    'z'?: number;
    'm'?: number;
    'coordinateValue'?: Coordinate | null;
    'isValid'?: boolean;
}
export interface CoordinateSequence {
    'dimension'?: number;
    'measures'?: number;
    'spatial'?: number;
    'ordinates'?: number;
    'hasZ'?: boolean;
    'hasM'?: boolean;
    'zOrdinateIndex'?: number;
    'mOrdinateIndex'?: number;
    'first'?: Coordinate | null;
    'last'?: Coordinate2 | null;
    'count'?: number;
}
export interface CoordinateSequenceFactory {
    'ordinates'?: number;
}
export interface CreateReservationRequest {
    'spotId': string;
    'startUtc': string;
    'endUtc': string;
}
export interface CreateSpotRequest {
    'name': string;
    'description': string | null;
    'location': Point3;
}
export interface Envelope {
    'isNull'?: boolean;
    'width'?: number;
    'height'?: number;
    'diameter'?: number;
    'minX'?: number;
    'maxX'?: number;
    'minY'?: number;
    'maxY'?: number;
    'area'?: number;
    'minExtent'?: number;
    'maxExtent'?: number;
    'centre'?: Coordinate2 | null;
}
export interface Geometry {
    'factory'?: GeometryFactory | null;
    'userData'?: any;
    'srid'?: number;
    'geometryType'?: string | null;
    'ogcGeometryType'?: number;
    'precisionModel'?: PrecisionModel | null;
    'coordinate'?: Coordinate2 | null;
    'coordinates'?: Array<any> | null;
    'numPoints'?: number;
    'numGeometries'?: number;
    'isSimple'?: boolean;
    'isValid'?: boolean;
    'isEmpty'?: boolean;
    'area'?: number;
    'length'?: number;
    'centroid'?: Point | null;
    'interiorPoint'?: any | null;
    'pointOnSurface'?: any | null;
    'dimension'?: number;
    'boundary'?: Geometry | null;
    'boundaryDimension'?: number;
    'envelope'?: Geometry | null;
    'envelopeInternal'?: any | null;
    'isRectangle'?: boolean;
}
export interface GeometryFactory {
    'precisionModel'?: PrecisionModel | null;
    'coordinateSequenceFactory'?: CoordinateSequenceFactory | null;
    'srid'?: number;
    'geometryServices'?: NtsGeometryServices | null;
}
export interface LoginRequest {
    'email': string;
    'password': string;
}
export interface NtsGeometryServices {
    'geometryOverlay'?: object | null;
    'coordinateEqualityComparer'?: object | null;
    'defaultSRID'?: number;
    'defaultCoordinateSequenceFactory'?: CoordinateSequenceFactory | null;
    'defaultPrecisionModel'?: PrecisionModel | null;
}
export interface Point {
    'coordinateSequence'?: CoordinateSequence | null;
    'coordinates'?: Array<Coordinate3> | null;
    'numPoints'?: number;
    'isEmpty'?: boolean;
    'dimension'?: number;
    'boundaryDimension'?: number;
    'x'?: number;
    'y'?: number;
    'coordinate'?: Coordinate2 | null;
    'geometryType'?: string | null;
    'ogcGeometryType'?: number;
    'boundary'?: Geometry | null;
    'z'?: number;
    'm'?: number;
    'factory'?: any | null;
    'userData'?: any;
    'srid'?: number;
    'precisionModel'?: any | null;
    'numGeometries'?: number;
    'isSimple'?: boolean;
    'isValid'?: boolean;
    'area'?: number;
    'length'?: number;
    'centroid'?: any | null;
    'interiorPoint'?: any | null;
    'pointOnSurface'?: any | null;
    'envelope'?: Geometry | null;
    'envelopeInternal'?: any | null;
    'isRectangle'?: boolean;
}
export interface Point2 {
    'coordinateSequence'?: any | null;
    'coordinates'?: Array<Coordinate3> | null;
    'numPoints'?: number;
    'isEmpty'?: boolean;
    'dimension'?: number;
    'boundaryDimension'?: number;
    'x'?: number;
    'y'?: number;
    'coordinate'?: any | null;
    'geometryType'?: string | null;
    'ogcGeometryType'?: number;
    'boundary'?: any | null;
    'z'?: number;
    'm'?: number;
    'factory'?: any | null;
    'userData'?: any;
    'srid'?: number;
    'precisionModel'?: any | null;
    'numGeometries'?: number;
    'isSimple'?: boolean;
    'isValid'?: boolean;
    'area'?: number;
    'length'?: number;
    'centroid'?: any | null;
    'interiorPoint'?: any | null;
    'pointOnSurface'?: any | null;
    'envelope'?: Geometry | null;
    'envelopeInternal'?: any | null;
    'isRectangle'?: boolean;
}
export interface Point3 {
    'coordinateSequence'?: CoordinateSequence | null;
    'coordinates'?: Array<Coordinate3> | null;
    'numPoints'?: number;
    'isEmpty'?: boolean;
    'dimension'?: number;
    'boundaryDimension'?: number;
    'x'?: number;
    'y'?: number;
    'coordinate'?: Coordinate2 | null;
    'geometryType'?: string | null;
    'ogcGeometryType'?: number;
    'boundary'?: Geometry | null;
    'z'?: number;
    'm'?: number;
    'factory'?: any | null;
    'userData'?: any;
    'srid'?: number;
    'precisionModel'?: any | null;
    'numGeometries'?: number;
    'isSimple'?: boolean;
    'isValid'?: boolean;
    'area'?: number;
    'length'?: number;
    'centroid'?: any | null;
    'interiorPoint'?: any | null;
    'pointOnSurface'?: any | null;
    'envelope'?: Geometry | null;
    'envelopeInternal'?: any | null;
    'isRectangle'?: boolean;
}
export interface PrecisionModel {
    'isFloating'?: boolean;
    'maximumSignificantDigits'?: number;
    'scale'?: number;
    'gridSize'?: number;
    'precisionModelType'?: number;
}
export interface RegisterRequest {
    'email': string;
    'password': string;
}
export interface ReservationDto {
    'id': string;
    'spotId': string;
    'userId': string;
    'startUtc': string;
    'endUtc': string;
    'status': string;
    'createdAtUtc': string;
    'approvedAtUtc': string | null;
    'cancelledAtUtc': string | null;
}
export interface SpotDto {
    'id': string;
    'name': string;
    'description': string | null;
    'isActive': boolean;
    'createdAtUtc': string;
    'location': Point | null;
}
export interface UpdateSpotRequest {
    'name': string;
    'description': string | null;
    'isActive': boolean;
    'location': Point | null;
}

/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthLoginPost: async (loginRequest: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('apiAuthLoginPost', 'loginRequest', loginRequest)
            const localVarPath = `/api/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RegisterRequest} registerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthRegisterPost: async (registerRequest: RegisterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerRequest' is not null or undefined
            assertParamExists('apiAuthRegisterPost', 'registerRequest', registerRequest)
            const localVarPath = `/api/auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthLoginPost(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthLoginPost(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.apiAuthLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RegisterRequest} registerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthRegisterPost(registerRequest: RegisterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthRegisterPost(registerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.apiAuthRegisterPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthLoginPost(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<AuthResponse> {
            return localVarFp.apiAuthLoginPost(loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RegisterRequest} registerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthRegisterPost(registerRequest: RegisterRequest, options?: RawAxiosRequestConfig): AxiosPromise<AuthResponse> {
            return localVarFp.apiAuthRegisterPost(registerRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @param {LoginRequest} loginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiAuthLoginPost(loginRequest: LoginRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).apiAuthLoginPost(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RegisterRequest} registerRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiAuthRegisterPost(registerRequest: RegisterRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).apiAuthRegisterPost(registerRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ReservationsApi - axios parameter creator
 */
export const ReservationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} spotId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationsBySpotSpotIdGet: async (spotId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'spotId' is not null or undefined
            assertParamExists('apiReservationsBySpotSpotIdGet', 'spotId', spotId)
            const localVarPath = `/api/reservations/by-spot/{spotId}`
                .replace(`{${"spotId"}}`, encodeURIComponent(String(spotId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationsIdCancelPost: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiReservationsIdCancelPost', 'id', id)
            const localVarPath = `/api/reservations/{id}/cancel`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationsIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiReservationsIdGet', 'id', id)
            const localVarPath = `/api/reservations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationsMineGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/reservations/mine`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreateReservationRequest} createReservationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationsPost: async (createReservationRequest: CreateReservationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createReservationRequest' is not null or undefined
            assertParamExists('apiReservationsPost', 'createReservationRequest', createReservationRequest)
            const localVarPath = `/api/reservations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createReservationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReservationsApi - functional programming interface
 */
export const ReservationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReservationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} spotId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReservationsBySpotSpotIdGet(spotId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ReservationDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReservationsBySpotSpotIdGet(spotId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReservationsApi.apiReservationsBySpotSpotIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReservationsIdCancelPost(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReservationsIdCancelPost(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReservationsApi.apiReservationsIdCancelPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReservationsIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReservationDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReservationsIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReservationsApi.apiReservationsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReservationsMineGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ReservationDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReservationsMineGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReservationsApi.apiReservationsMineGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CreateReservationRequest} createReservationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReservationsPost(createReservationRequest: CreateReservationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReservationDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReservationsPost(createReservationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReservationsApi.apiReservationsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReservationsApi - factory interface
 */
export const ReservationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReservationsApiFp(configuration)
    return {
        /**
         * 
         * @param {string} spotId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationsBySpotSpotIdGet(spotId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ReservationDto>> {
            return localVarFp.apiReservationsBySpotSpotIdGet(spotId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationsIdCancelPost(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiReservationsIdCancelPost(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationsIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ReservationDto> {
            return localVarFp.apiReservationsIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationsMineGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<ReservationDto>> {
            return localVarFp.apiReservationsMineGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CreateReservationRequest} createReservationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationsPost(createReservationRequest: CreateReservationRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReservationDto> {
            return localVarFp.apiReservationsPost(createReservationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReservationsApi - object-oriented interface
 */
export class ReservationsApi extends BaseAPI {
    /**
     * 
     * @param {string} spotId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReservationsBySpotSpotIdGet(spotId: string, options?: RawAxiosRequestConfig) {
        return ReservationsApiFp(this.configuration).apiReservationsBySpotSpotIdGet(spotId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReservationsIdCancelPost(id: string, options?: RawAxiosRequestConfig) {
        return ReservationsApiFp(this.configuration).apiReservationsIdCancelPost(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReservationsIdGet(id: string, options?: RawAxiosRequestConfig) {
        return ReservationsApiFp(this.configuration).apiReservationsIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReservationsMineGet(options?: RawAxiosRequestConfig) {
        return ReservationsApiFp(this.configuration).apiReservationsMineGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CreateReservationRequest} createReservationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReservationsPost(createReservationRequest: CreateReservationRequest, options?: RawAxiosRequestConfig) {
        return ReservationsApiFp(this.configuration).apiReservationsPost(createReservationRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SpotsApi - axios parameter creator
 */
export const SpotsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {boolean} [onlyActive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsGet: async (onlyActive?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/spots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (onlyActive !== undefined) {
                localVarQueryParameter['onlyActive'] = onlyActive;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsIdDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiSpotsIdDelete', 'id', id)
            const localVarPath = `/api/spots/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiSpotsIdGet', 'id', id)
            const localVarPath = `/api/spots/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateSpotRequest} updateSpotRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsIdPut: async (id: string, updateSpotRequest: UpdateSpotRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiSpotsIdPut', 'id', id)
            // verify required parameter 'updateSpotRequest' is not null or undefined
            assertParamExists('apiSpotsIdPut', 'updateSpotRequest', updateSpotRequest)
            const localVarPath = `/api/spots/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateSpotRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreateSpotRequest} createSpotRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsPost: async (createSpotRequest: CreateSpotRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createSpotRequest' is not null or undefined
            assertParamExists('apiSpotsPost', 'createSpotRequest', createSpotRequest)
            const localVarPath = `/api/spots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSpotRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SpotsApi - functional programming interface
 */
export const SpotsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SpotsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {boolean} [onlyActive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSpotsGet(onlyActive?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SpotDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSpotsGet(onlyActive, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpotsApi.apiSpotsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSpotsIdDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSpotsIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpotsApi.apiSpotsIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSpotsIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SpotDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSpotsIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpotsApi.apiSpotsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateSpotRequest} updateSpotRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSpotsIdPut(id: string, updateSpotRequest: UpdateSpotRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SpotDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSpotsIdPut(id, updateSpotRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpotsApi.apiSpotsIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CreateSpotRequest} createSpotRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSpotsPost(createSpotRequest: CreateSpotRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SpotDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSpotsPost(createSpotRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpotsApi.apiSpotsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SpotsApi - factory interface
 */
export const SpotsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SpotsApiFp(configuration)
    return {
        /**
         * 
         * @param {boolean} [onlyActive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsGet(onlyActive?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<Array<SpotDto>> {
            return localVarFp.apiSpotsGet(onlyActive, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsIdDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiSpotsIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<SpotDto> {
            return localVarFp.apiSpotsIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateSpotRequest} updateSpotRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsIdPut(id: string, updateSpotRequest: UpdateSpotRequest, options?: RawAxiosRequestConfig): AxiosPromise<SpotDto> {
            return localVarFp.apiSpotsIdPut(id, updateSpotRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CreateSpotRequest} createSpotRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsPost(createSpotRequest: CreateSpotRequest, options?: RawAxiosRequestConfig): AxiosPromise<SpotDto> {
            return localVarFp.apiSpotsPost(createSpotRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SpotsApi - object-oriented interface
 */
export class SpotsApi extends BaseAPI {
    /**
     * 
     * @param {boolean} [onlyActive] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSpotsGet(onlyActive?: boolean, options?: RawAxiosRequestConfig) {
        return SpotsApiFp(this.configuration).apiSpotsGet(onlyActive, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSpotsIdDelete(id: string, options?: RawAxiosRequestConfig) {
        return SpotsApiFp(this.configuration).apiSpotsIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSpotsIdGet(id: string, options?: RawAxiosRequestConfig) {
        return SpotsApiFp(this.configuration).apiSpotsIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {UpdateSpotRequest} updateSpotRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSpotsIdPut(id: string, updateSpotRequest: UpdateSpotRequest, options?: RawAxiosRequestConfig) {
        return SpotsApiFp(this.configuration).apiSpotsIdPut(id, updateSpotRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CreateSpotRequest} createSpotRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSpotsPost(createSpotRequest: CreateSpotRequest, options?: RawAxiosRequestConfig) {
        return SpotsApiFp(this.configuration).apiSpotsPost(createSpotRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



