/* tslint:disable */
/* eslint-disable */
/**
 * SpotReservation.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaymentInfoDto } from './payment-info-dto';

export interface ReservationDto {
    'id': string;
    'spotId': string;
    'startUtc': string;
    'endUtc': string;
    'status': string;
    'paymentInfoDto': PaymentInfoDto;
    'createdAtUtc': string;
    'approvedAtUtc': string | null;
    'cancelledAtUtc': string | null;
}

