/* tslint:disable */
/* eslint-disable */
/**
 * SpotReservation.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SpotDto } from './spot-dto';

export interface ReservationPageDto {
    'id': string;
    'name': string;
    'description': string | null;
    'mapCenter': any | null;
    'mapZoom': number;
    'mapMinZoom': number;
    'mapMaxZoom': number;
    'iban': string | null;
    'termsAndConditionsUrl': string | null;
    'openingHoursJson': string | null;
    'contactEmail': string | null;
    'contactPhone': string | null;
    'spots': Array<SpotDto>;
}

