/* tslint:disable */
/* eslint-disable */
/**
 * SpotReservation.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateReservationPageRequest {
    'name': string;
    'description': string | null;
    'address': string | null;
    'addressLocation': any | null;
    'mapCenter': any | null;
    'mapZoom': number;
    'mapMinZoom': number;
    'mapMaxZoom': number;
    'pricePerDay': number;
    'iban': string;
    'currency': string;
    'termsAndConditionsUrl': string | null;
    'openingHoursJson': string | null;
    'contactName': string;
    'contactEmail': string;
    'contactPhone': string;
}

