/* tslint:disable */
/* eslint-disable */
/**
 * SpotReservation.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * FilesApi - axios parameter creator
 */
export const FilesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} bucket 
         * @param {string} objectKey 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiFilesBucketObjectKeyGet: async (bucket: string, objectKey: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bucket' is not null or undefined
            assertParamExists('apiFilesBucketObjectKeyGet', 'bucket', bucket)
            // verify required parameter 'objectKey' is not null or undefined
            assertParamExists('apiFilesBucketObjectKeyGet', 'objectKey', objectKey)
            const localVarPath = `/api/files/{bucket}/{objectKey}`
                .replace(`{${"bucket"}}`, encodeURIComponent(String(bucket)))
                .replace(`{${"objectKey"}}`, encodeURIComponent(String(objectKey)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} bucket 
         * @param {File} file 
         * @param {string} [objectKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiFilesBucketPost: async (bucket: string, file: File, objectKey?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bucket' is not null or undefined
            assertParamExists('apiFilesBucketPost', 'bucket', bucket)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('apiFilesBucketPost', 'file', file)
            const localVarPath = `/api/files/{bucket}`
                .replace(`{${"bucket"}}`, encodeURIComponent(String(bucket)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            if (objectKey !== undefined) {
                localVarQueryParameter['objectKey'] = objectKey;
            }


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FilesApi - functional programming interface
 */
export const FilesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FilesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} bucket 
         * @param {string} objectKey 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiFilesBucketObjectKeyGet(bucket: string, objectKey: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiFilesBucketObjectKeyGet(bucket, objectKey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.apiFilesBucketObjectKeyGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} bucket 
         * @param {File} file 
         * @param {string} [objectKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiFilesBucketPost(bucket: string, file: File, objectKey?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiFilesBucketPost(bucket, file, objectKey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.apiFilesBucketPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FilesApi - factory interface
 */
export const FilesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FilesApiFp(configuration)
    return {
        /**
         * 
         * @param {string} bucket 
         * @param {string} objectKey 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiFilesBucketObjectKeyGet(bucket: string, objectKey: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiFilesBucketObjectKeyGet(bucket, objectKey, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} bucket 
         * @param {File} file 
         * @param {string} [objectKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiFilesBucketPost(bucket: string, file: File, objectKey?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiFilesBucketPost(bucket, file, objectKey, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FilesApi - object-oriented interface
 */
export class FilesApi extends BaseAPI {
    /**
     * 
     * @param {string} bucket 
     * @param {string} objectKey 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiFilesBucketObjectKeyGet(bucket: string, objectKey: string, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).apiFilesBucketObjectKeyGet(bucket, objectKey, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} bucket 
     * @param {File} file 
     * @param {string} [objectKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiFilesBucketPost(bucket: string, file: File, objectKey?: string, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).apiFilesBucketPost(bucket, file, objectKey, options).then((request) => request(this.axios, this.basePath));
    }
}

