/* tslint:disable */
/* eslint-disable */
/**
 * SpotReservation.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateReservationPageRequest } from '../model';
// @ts-ignore
import type { ReservationPageDto } from '../model';
// @ts-ignore
import type { UpdateReservationPageRequest } from '../model';
/**
 * ReservationPagesApi - axios parameter creator
 */
export const ReservationPagesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationPagesIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiReservationPagesIdGet', 'id', id)
            const localVarPath = `/api/reservation-pages/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateReservationPageRequest} updateReservationPageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationPagesIdPut: async (id: string, updateReservationPageRequest: UpdateReservationPageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiReservationPagesIdPut', 'id', id)
            // verify required parameter 'updateReservationPageRequest' is not null or undefined
            assertParamExists('apiReservationPagesIdPut', 'updateReservationPageRequest', updateReservationPageRequest)
            const localVarPath = `/api/reservation-pages/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateReservationPageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreateReservationPageRequest} createReservationPageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationPagesPost: async (createReservationPageRequest: CreateReservationPageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createReservationPageRequest' is not null or undefined
            assertParamExists('apiReservationPagesPost', 'createReservationPageRequest', createReservationPageRequest)
            const localVarPath = `/api/reservation-pages`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createReservationPageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReservationPagesApi - functional programming interface
 */
export const ReservationPagesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReservationPagesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReservationPagesIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReservationPageDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReservationPagesIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReservationPagesApi.apiReservationPagesIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateReservationPageRequest} updateReservationPageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReservationPagesIdPut(id: string, updateReservationPageRequest: UpdateReservationPageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReservationPageDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReservationPagesIdPut(id, updateReservationPageRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReservationPagesApi.apiReservationPagesIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CreateReservationPageRequest} createReservationPageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiReservationPagesPost(createReservationPageRequest: CreateReservationPageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReservationPageDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiReservationPagesPost(createReservationPageRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReservationPagesApi.apiReservationPagesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReservationPagesApi - factory interface
 */
export const ReservationPagesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReservationPagesApiFp(configuration)
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationPagesIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ReservationPageDto> {
            return localVarFp.apiReservationPagesIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateReservationPageRequest} updateReservationPageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationPagesIdPut(id: string, updateReservationPageRequest: UpdateReservationPageRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReservationPageDto> {
            return localVarFp.apiReservationPagesIdPut(id, updateReservationPageRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CreateReservationPageRequest} createReservationPageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiReservationPagesPost(createReservationPageRequest: CreateReservationPageRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReservationPageDto> {
            return localVarFp.apiReservationPagesPost(createReservationPageRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReservationPagesApi - object-oriented interface
 */
export class ReservationPagesApi extends BaseAPI {
    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReservationPagesIdGet(id: string, options?: RawAxiosRequestConfig) {
        return ReservationPagesApiFp(this.configuration).apiReservationPagesIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {UpdateReservationPageRequest} updateReservationPageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReservationPagesIdPut(id: string, updateReservationPageRequest: UpdateReservationPageRequest, options?: RawAxiosRequestConfig) {
        return ReservationPagesApiFp(this.configuration).apiReservationPagesIdPut(id, updateReservationPageRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CreateReservationPageRequest} createReservationPageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiReservationPagesPost(createReservationPageRequest: CreateReservationPageRequest, options?: RawAxiosRequestConfig) {
        return ReservationPagesApiFp(this.configuration).apiReservationPagesPost(createReservationPageRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

