/* tslint:disable */
/* eslint-disable */
/**
 * SpotReservation.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateSpotRequest } from '../model';
// @ts-ignore
import type { SpotDto } from '../model';
// @ts-ignore
import type { UpdateSpotRequest } from '../model';
/**
 * SpotsApi - axios parameter creator
 */
export const SpotsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} pageId 
         * @param {boolean} [onlyActive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsByPagePageIdGet: async (pageId: string, onlyActive?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageId' is not null or undefined
            assertParamExists('apiSpotsByPagePageIdGet', 'pageId', pageId)
            const localVarPath = `/api/spots/by-page/{pageId}`
                .replace(`{${"pageId"}}`, encodeURIComponent(String(pageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (onlyActive !== undefined) {
                localVarQueryParameter['onlyActive'] = onlyActive;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {boolean} [onlyActive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsGet: async (onlyActive?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/spots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (onlyActive !== undefined) {
                localVarQueryParameter['onlyActive'] = onlyActive;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsIdDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiSpotsIdDelete', 'id', id)
            const localVarPath = `/api/spots/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiSpotsIdGet', 'id', id)
            const localVarPath = `/api/spots/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateSpotRequest} updateSpotRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsIdPut: async (id: string, updateSpotRequest: UpdateSpotRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiSpotsIdPut', 'id', id)
            // verify required parameter 'updateSpotRequest' is not null or undefined
            assertParamExists('apiSpotsIdPut', 'updateSpotRequest', updateSpotRequest)
            const localVarPath = `/api/spots/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateSpotRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreateSpotRequest} createSpotRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsPost: async (createSpotRequest: CreateSpotRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createSpotRequest' is not null or undefined
            assertParamExists('apiSpotsPost', 'createSpotRequest', createSpotRequest)
            const localVarPath = `/api/spots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSpotRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SpotsApi - functional programming interface
 */
export const SpotsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SpotsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} pageId 
         * @param {boolean} [onlyActive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSpotsByPagePageIdGet(pageId: string, onlyActive?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SpotDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSpotsByPagePageIdGet(pageId, onlyActive, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpotsApi.apiSpotsByPagePageIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {boolean} [onlyActive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSpotsGet(onlyActive?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SpotDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSpotsGet(onlyActive, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpotsApi.apiSpotsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSpotsIdDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSpotsIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpotsApi.apiSpotsIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSpotsIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SpotDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSpotsIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpotsApi.apiSpotsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateSpotRequest} updateSpotRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSpotsIdPut(id: string, updateSpotRequest: UpdateSpotRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SpotDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSpotsIdPut(id, updateSpotRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpotsApi.apiSpotsIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CreateSpotRequest} createSpotRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSpotsPost(createSpotRequest: CreateSpotRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SpotDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSpotsPost(createSpotRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpotsApi.apiSpotsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SpotsApi - factory interface
 */
export const SpotsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SpotsApiFp(configuration)
    return {
        /**
         * 
         * @param {string} pageId 
         * @param {boolean} [onlyActive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsByPagePageIdGet(pageId: string, onlyActive?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<Array<SpotDto>> {
            return localVarFp.apiSpotsByPagePageIdGet(pageId, onlyActive, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {boolean} [onlyActive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsGet(onlyActive?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<Array<SpotDto>> {
            return localVarFp.apiSpotsGet(onlyActive, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsIdDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiSpotsIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<SpotDto> {
            return localVarFp.apiSpotsIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateSpotRequest} updateSpotRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsIdPut(id: string, updateSpotRequest: UpdateSpotRequest, options?: RawAxiosRequestConfig): AxiosPromise<SpotDto> {
            return localVarFp.apiSpotsIdPut(id, updateSpotRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CreateSpotRequest} createSpotRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotsPost(createSpotRequest: CreateSpotRequest, options?: RawAxiosRequestConfig): AxiosPromise<SpotDto> {
            return localVarFp.apiSpotsPost(createSpotRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SpotsApi - object-oriented interface
 */
export class SpotsApi extends BaseAPI {
    /**
     * 
     * @param {string} pageId 
     * @param {boolean} [onlyActive] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSpotsByPagePageIdGet(pageId: string, onlyActive?: boolean, options?: RawAxiosRequestConfig) {
        return SpotsApiFp(this.configuration).apiSpotsByPagePageIdGet(pageId, onlyActive, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {boolean} [onlyActive] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSpotsGet(onlyActive?: boolean, options?: RawAxiosRequestConfig) {
        return SpotsApiFp(this.configuration).apiSpotsGet(onlyActive, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSpotsIdDelete(id: string, options?: RawAxiosRequestConfig) {
        return SpotsApiFp(this.configuration).apiSpotsIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSpotsIdGet(id: string, options?: RawAxiosRequestConfig) {
        return SpotsApiFp(this.configuration).apiSpotsIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {UpdateSpotRequest} updateSpotRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSpotsIdPut(id: string, updateSpotRequest: UpdateSpotRequest, options?: RawAxiosRequestConfig) {
        return SpotsApiFp(this.configuration).apiSpotsIdPut(id, updateSpotRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CreateSpotRequest} createSpotRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSpotsPost(createSpotRequest: CreateSpotRequest, options?: RawAxiosRequestConfig) {
        return SpotsApiFp(this.configuration).apiSpotsPost(createSpotRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

