/* tslint:disable */
/* eslint-disable */
/**
 * SpotReservation.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SpotPhotoDto } from '../model';
/**
 * SpotPhotosApi - axios parameter creator
 */
export const SpotPhotosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} spotId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotPhotosBySpotSpotIdGet: async (spotId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'spotId' is not null or undefined
            assertParamExists('apiSpotPhotosBySpotSpotIdGet', 'spotId', spotId)
            const localVarPath = `/api/spot-photos/by-spot/{spotId}`
                .replace(`{${"spotId"}}`, encodeURIComponent(String(spotId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotPhotosIdDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiSpotPhotosIdDelete', 'id', id)
            const localVarPath = `/api/spot-photos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} spotId 
         * @param {number} sortOrder 
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotPhotosPost: async (spotId: string, sortOrder: number, file: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'spotId' is not null or undefined
            assertParamExists('apiSpotPhotosPost', 'spotId', spotId)
            // verify required parameter 'sortOrder' is not null or undefined
            assertParamExists('apiSpotPhotosPost', 'sortOrder', sortOrder)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('apiSpotPhotosPost', 'file', file)
            const localVarPath = `/api/spot-photos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            if (spotId !== undefined) {
                localVarQueryParameter['spotId'] = spotId;
            }

            if (sortOrder !== undefined) {
                localVarQueryParameter['sortOrder'] = sortOrder;
            }


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SpotPhotosApi - functional programming interface
 */
export const SpotPhotosApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SpotPhotosApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} spotId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSpotPhotosBySpotSpotIdGet(spotId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SpotPhotoDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSpotPhotosBySpotSpotIdGet(spotId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpotPhotosApi.apiSpotPhotosBySpotSpotIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSpotPhotosIdDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSpotPhotosIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpotPhotosApi.apiSpotPhotosIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} spotId 
         * @param {number} sortOrder 
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSpotPhotosPost(spotId: string, sortOrder: number, file: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SpotPhotoDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSpotPhotosPost(spotId, sortOrder, file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpotPhotosApi.apiSpotPhotosPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SpotPhotosApi - factory interface
 */
export const SpotPhotosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SpotPhotosApiFp(configuration)
    return {
        /**
         * 
         * @param {string} spotId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotPhotosBySpotSpotIdGet(spotId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<SpotPhotoDto>> {
            return localVarFp.apiSpotPhotosBySpotSpotIdGet(spotId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotPhotosIdDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiSpotPhotosIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} spotId 
         * @param {number} sortOrder 
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSpotPhotosPost(spotId: string, sortOrder: number, file: File, options?: RawAxiosRequestConfig): AxiosPromise<SpotPhotoDto> {
            return localVarFp.apiSpotPhotosPost(spotId, sortOrder, file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SpotPhotosApi - object-oriented interface
 */
export class SpotPhotosApi extends BaseAPI {
    /**
     * 
     * @param {string} spotId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSpotPhotosBySpotSpotIdGet(spotId: string, options?: RawAxiosRequestConfig) {
        return SpotPhotosApiFp(this.configuration).apiSpotPhotosBySpotSpotIdGet(spotId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSpotPhotosIdDelete(id: string, options?: RawAxiosRequestConfig) {
        return SpotPhotosApiFp(this.configuration).apiSpotPhotosIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} spotId 
     * @param {number} sortOrder 
     * @param {File} file 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiSpotPhotosPost(spotId: string, sortOrder: number, file: File, options?: RawAxiosRequestConfig) {
        return SpotPhotosApiFp(this.configuration).apiSpotPhotosPost(spotId, sortOrder, file, options).then((request) => request(this.axios, this.basePath));
    }
}

