// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpotReservation.Infrastructure.Persistence;

#nullable disable

namespace SpotReservation.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpotReservation.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReservationPageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SpotId")
                        .HasColumnType("uuid");

                    b.Property<string>("VariableSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationPageId");

                    b.HasIndex("SpotId");

                    b.ToTable("reservations", (string)null);

                    b.HasDiscriminator<string>("status").HasValue("Reservation");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SpotReservation.Domain.Entities.ReservationPage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TermsAndConditionsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("reservation_pages", (string)null);
                });

            modelBuilder.Entity("SpotReservation.Domain.Entities.Spot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReservationPageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ReservationPageId");

                    b.ToTable("spots", (string)null);
                });

            modelBuilder.Entity("SpotReservation.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SpotReservation.Domain.Entities.ApprovedReservation", b =>
                {
                    b.HasBaseType("SpotReservation.Domain.Entities.Reservation");

                    b.Property<DateTime>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.HasDiscriminator().HasValue("Approved");
                });

            modelBuilder.Entity("SpotReservation.Domain.Entities.CancelledReservation", b =>
                {
                    b.HasBaseType("SpotReservation.Domain.Entities.Reservation");

                    b.Property<DateTime>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.HasDiscriminator().HasValue("Cancelled");
                });

            modelBuilder.Entity("SpotReservation.Domain.Entities.PendingReservation", b =>
                {
                    b.HasBaseType("SpotReservation.Domain.Entities.Reservation");

                    b.HasDiscriminator().HasValue("Pending");
                });

            modelBuilder.Entity("SpotReservation.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("SpotReservation.Domain.Entities.ReservationPage", "ReservationPage")
                        .WithMany()
                        .HasForeignKey("ReservationPageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpotReservation.Domain.Entities.Spot", "Spot")
                        .WithMany("Reservations")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SpotReservation.Domain.ValueObjects.TimeRange", "Period", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("end_utc");

                            b1.Property<DateTime>("StartUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("start_utc");

                            b1.HasKey("ReservationId");

                            b1.HasIndex("EndUtc");

                            b1.HasIndex("StartUtc");

                            b1.ToTable("reservations");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("ReservationPage");

                    b.Navigation("Spot");
                });

            modelBuilder.Entity("SpotReservation.Domain.Entities.ReservationPage", b =>
                {
                    b.OwnsOne("SpotReservation.Domain.Entities.ContactInformations", "ContactInformations", b1 =>
                        {
                            b1.Property<string>("ReservationPageId")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("OpeningHoursJson")
                                .HasColumnType("text")
                                .HasColumnName("contact_opening_hours_json");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("ReservationPageId");

                            b1.ToTable("reservation_pages");

                            b1.WithOwner()
                                .HasForeignKey("ReservationPageId");
                        });

                    b.OwnsOne("SpotReservation.Domain.Entities.MapOptions", "MapOptions", b1 =>
                        {
                            b1.Property<string>("ReservationPageId")
                                .HasColumnType("text");

                            b1.Property<Point>("Center")
                                .HasColumnType("geometry(Point, 4326)")
                                .HasColumnName("map_center");

                            b1.Property<int>("MaxZoom")
                                .HasColumnType("integer")
                                .HasColumnName("map_max_zoom");

                            b1.Property<int>("MinZoom")
                                .HasColumnType("integer")
                                .HasColumnName("map_min_zoom");

                            b1.Property<int>("Zoom")
                                .HasColumnType("integer")
                                .HasColumnName("map_zoom");

                            b1.HasKey("ReservationPageId");

                            b1.ToTable("reservation_pages");

                            b1.WithOwner()
                                .HasForeignKey("ReservationPageId");
                        });

                    b.OwnsOne("SpotReservation.Domain.Entities.OwnerPayementInformations", "PayementInformations", b1 =>
                        {
                            b1.Property<string>("ReservationPageId")
                                .HasColumnType("text");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.Property<string>("Iban")
                                .IsRequired()
                                .HasMaxLength(34)
                                .HasColumnType("character varying(34)");

                            b1.HasKey("ReservationPageId");

                            b1.ToTable("reservation_pages");

                            b1.WithOwner()
                                .HasForeignKey("ReservationPageId");
                        });

                    b.Navigation("ContactInformations")
                        .IsRequired();

                    b.Navigation("MapOptions")
                        .IsRequired();

                    b.Navigation("PayementInformations")
                        .IsRequired();
                });

            modelBuilder.Entity("SpotReservation.Domain.Entities.Spot", b =>
                {
                    b.HasOne("SpotReservation.Domain.Entities.ReservationPage", "ReservationPage")
                        .WithMany("Spots")
                        .HasForeignKey("ReservationPageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReservationPage");
                });

            modelBuilder.Entity("SpotReservation.Domain.Entities.ReservationPage", b =>
                {
                    b.Navigation("Spots");
                });

            modelBuilder.Entity("SpotReservation.Domain.Entities.Spot", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
